config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # mount ContentfulRails::Engine => '/contentful'

  resources :recipes, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
require 'contentful_model'

class Recipe < ContentfulModel::Base
   self.content_type_id = "recipe"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :load_recipe, only: [:show]

  def index
    @recipes = Recipe.all.load
  end

  def show
  end

  private

  def load_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Marley Spoon', recipes_path, class: 'navbar-brand', :style => 'color: #accaf9;'%>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class='<%= 'active' if request.path.starts_with?(recipes_path) %>'>
            <%= link_to 'View Menu', recipes_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarleySpoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header', locals: {} %>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="container">
<h4>Recipes</h4>
  <% @recipes.each do |recipe| %>
    <div class="col-md-4">
      <div class="card bg-dark text-white">
        <%= link_to recipe_path(id: recipe.id) do %>
          <img class="card-img zoom-in" src="<%= recipe.photo.url %>" alt="<%= recipe.title %>">
        <% end %>
        <div class="card-img-overlay d-flex flex-column">
          <h3 class="card-text font-weight-bold"><span class="mr-auto"><%= recipe.title %></span></h3>
          <div class="mt-auto"><%= link_to 'View Recipe', recipe_path(id: recipe.id), class: "btn btn-primary" %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="width-80 margin-0-auto">
    <img class="card-img" src="<%= @recipe.photo.url %>" alt="<%= @recipe.title %>">
    <div class="card-img-overlay d-flex flex-column">
      <h3 class="card-text font-weight-bold"><%= @recipe.title %></h3>
      <div class="clear width-80 left">
        &nbsp
        <% @recipe.tags&.each do |tag| %>
          <span class="tag"><%= tag.name %></span>
        <% end %>
      </div>
      <p class="font-weight-bold">Calories: <%= @recipe.calories %></p>
      <div class="mt-10">
        <p class="card-text"><span class="mr-auto"><%= auto_link(@recipe.description) %></span></p>
      </div>
    </div>
    <hr class="clear">
    <p>Shared with you by: <span class='text-green'><%= @recipe.chef&.name %></span></p>
  </div>
</div>